baseURL = "https://sergehuber.github.io/emedswiss-hugo-test/"
languageCode = "en-us"
title = "EmedSwiss Hugo Test Site"
theme = "github.com/theNewDynamic/gohugo-theme-ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[pagination]
  pagerSize = 3

googleAnalytics = ""
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[languages]
  [languages.en]
    title = "EmedSwiss"
    weight = 1
    contentDir = "content/en"
  
  [languages.fr]
    title = "EmedSwiss Fr"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # Choose a background color from any on this page: https://tachyons.io/docs/themes/skins/
  # Preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/emedswiss"