name: Deploy Hugo site

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        TZ: UTC  # Ensure the build environment uses UTC
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Ensure the extended version is used

      - name: Cache Hugo modules
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Clear Hugo cache
        run: hugo --gc --minify

      - name: Clear Hugo destination directory
        run: hugo --cleanDestinationDir

      - name: Install Hugo Modules
        run: hugo mod get all

      - name: Build Hugo site
        run: hugo --minify --logLevel=DEBUG -F

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Output directory generated by Hugo
          publish_branch: gh-pages
          force_orphan: true
